spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dev
    username: dev
    password: dev
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
